language: node_js
node_js:
- '6'
- '7'
env:
  global:
  - secure: CetX10W3SCeTfvyM4c4GutdprDsRWdBgwc1Iw0eFW63Uphep1JYNhqy5oLRkGX7keBCJGmERr32Z5R0N+FWAyzP80qt1Cn4aoxaKvYsFbmW8Mmo5DaPKA0yH4NnnuQLd0kCObgh1ptaG/PMc4HxvgU1T5zkUdd3lwxUZcqd6jPA=
install:
- npm install
cache:
  directories:
  - node_modules
script:
- npm run-script jshint
- npm test
- npm run-script coveralls
- npm run-script test-dist
deploy:
  provider: npm
  api_key:
    secure: QkzADsSiH5QQlaxdLUz8NXG5CNIHa0w50nSwlB96pw2SpA5xUR4W21eq5ByhlLdsypRuvs4Y7CQAEoUYQj/K21HRC9CMTW5nt/nNFOtnpS0wQYgDe2CwAA1Ii9fmPYaLcb0zKl/pWPLL00qQzMcZjvBRtELgJ+EMYoI26ko54Kc=
  email:
    secure: eyruHLpKLpGuKPyQvVbRI8/08btHmD2dgPxr0levhxsC6+fY8fssu2ZEUlto4NINFLLDxjXXVEB1wTDrpkQaUpExGdwUpdBt6UGlgU1BAC6IyaQKDYGlavNJL9wppXRpSl7dV/N/Kfrt5bM6tcoDbZw71wqEnAu6TKYL1DXQTQk=
  on:
    branch: master
    tags: true
    node: '0.12'
